### PR TITLE
Update README.md with caching_sha2_password limitation

### PR DESCRIPTION
**Pull request by enortham**
Add caching_sha2_password limitation. I lost a lot of time trying to figure out why I couldn't authenticate and I think this should be in the README to save others in the future. Hopefully this will be fixed soon based on #26.

### CODE REVIEW

**Comment by andyjeffries** [comment]
I would change this to comment that it's the default configuration in the official Docker images too, otherwise people may not be aware of the setting and just think "I'm OK, I didn't change that option so I should be fine" and cause lots of wasted time.

**Comment by enortham** [comment]
Thanks @andyjeffries. I added that it's the default for MySQL 8 which should affect not only Docker but anything that uses 8.

**Comment by bensheldon** [comment]
Thank you for proposing this change! I made a few tweaks and will accept 👍🏻

**Comment by andyjeffries** [comment]
Hi @bensheldon you removed the part about it being default for MySQL 8 and for the MySQL 8 docker build? That feels like key information.

**Comment by andyjeffries** [comment]
Of course, this is something that @eileencodes is working on, so soon (for some definition...) this documentation change won't be necessary anyway.

Appreciate your work (all of you) on this great library, really looking forward to switching properly to it.

**Comment by eileencodes** [comment]
Closing in favor of https://github.com/trilogy-libraries/trilogy/pull/165

**Pull request closed without merging**
