### PR TITLE
Handle EADDRNOTAVAIL as a BaseConnectionError instead of SyscallError

### PR DESCRIPTION
**Pull request by dhruvCW**
instead of letting EADDRNOTAVAIL be handled as a generic SyscallError convert it to a BaseConnectionError instead, in this case we treat it as a a TRILOGY_DNS_ERROR so that the activerecord adapters handle it as a DBConnectionError.

fixes https://github.com/trilogy-libraries/activerecord-trilogy-adapter/issues/52

### CODE REVIEW

**Comment by jhawthorn** [comment]
I'm not sure I agree with the motivation here. A Trilogy::SyscallError is what will be raised here and what we'll raise for a number of other connection-related errors. It seems best to use the most specific error we can for the error we've encountered.

**Comment by dhruvCW** [comment]
>I'm not sure I agree with the motivation here. A Trilogy::SyscallError is what will be raised here and what we'll raise for a number of other connection-related errors. It seems best to use the most specific error we can for the error we've encountered.

don't you think it would make sense to raise an exception that is derived from a `Trilogy::ConnectionError` base ? I am thinking in terms of a use case like active_record adapter where it might be better to handle all connection errors rather than specific ones ?

In this case though I am not particularly invested anymore since it arises from an invalid system setup and thus is more of an outlier than other errors.

**Comment by jhawthorn** [comment]
I think it could make sense as a `Trilogy::ConnectionError`, but only if that was also done to the other `Trilogy::SyscallError::*` classes, which are effectively all "connection-level" errors.

thoughts @adrianna-chang-shopify @casperisfine ?

**Comment by casperisfine** [comment]
> thoughts

Yeah, that's why I don't like the syscall errors, I'd like to be able to `rescue Trilogy::BaseConnectionError` or something, and inheriting from `SystemCallError` prevents that :/

**Comment by adrianna-chang-shopify** [comment]
> Yeah, that's why I don't like the syscall errors, I'd like to be able to rescue Trilogy::BaseConnectionError

Yeah, I guess the idea with our approach was that consumers could generically rescue syscall errors as `Trilogy::Error`, but also use the raw syscall errs (e.g. `ECONNRESET`) for finer-tuned handling. Changing the syscall errors to include `Trilogy::BaseConnectionError` makes sense to me 👍

**Pull request closed without merging**
